apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    type: loki
    orgId: 1
    url: http://loki:3100
    uid: loki
    jsonData:
      manageAlerts: false
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"trace\":\"(\\w+?)\""
          name: derivedTraceId
          url: '$${__value.raw}'
