server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:tracing-demo-logback.xml
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG

tracing:
  demo:
    sidra: http://localhost:8080
    ira: http://localhost:8081
    rohan: http://localhost:8082