server:
  port: 8080

logging:
  config: classpath:tracing-demo-logback.xml
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG

tracing:
  demo:
    sidra: http://localhost:8080
    ira: http://localhost:8081
    rohan: http://localhost:8082