services:

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/config/:/etc/prometheus/"
      - "prometheus_data:/prometheus"
    command:
      - --log.level=debug
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - "loki_data:/loki"

#  k6-tracing:
#    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
#    environment:
#      - ENDPOINT=tempo:4317
#    restart: always
#    depends_on:
#      - tempo

  tempo:
    image: grafana/tempo:latest
    ports:
      - "4317:4317"
    volumes:
      - "./tempo/config/:/config/"
      - "tempo_data:/var/tempo"
    command: [ "--config.file=/config/tempo.yml" ]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
      - "grafana_data:/var/lib/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  sidra:
    image: raketeneinhorn/tracing-demo-sidra:0.0.1-SNAPSHOT
    depends_on:
      - ira
    ports:
      - "8080:8080"
    volumes:
      - "sidra_logs:/workspace/logs"
    environment:
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317/
      TRACING_DEMO_SIDRA: "${TRACING_DEMO_SIDRA}"
      TRACING_DEMO_IRA: "${TRACING_DEMO_IRA}"
      TRACING_DEMO_ROHAN: "${TRACING_DEMO_ROHAN}"

  sidra_promtail:
    depends_on:
      - loki
    image: grafana/promtail:latest
    volumes:
      - "./promtail/config/:/etc/promtail/"
      - "sidra_logs:/workspace/logs"
    command: [ "-config.file=/etc/promtail/promtail.yml", "-config.expand-env=true" ]

  ira:
    image: raketeneinhorn/tracing-demo-ira:0.0.1-SNAPSHOT
    depends_on:
      - rohan
    volumes:
      - "ira_logs:/workspace/logs"
    environment:
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317/
      TRACING_DEMO_SIDRA: "${TRACING_DEMO_SIDRA}"
      TRACING_DEMO_IRA: "${TRACING_DEMO_IRA}"
      TRACING_DEMO_ROHAN: "${TRACING_DEMO_ROHAN}"
  ira_promtail:
    depends_on:
      - loki
    image: grafana/promtail:latest
    volumes:
      - "./promtail/config/:/etc/promtail/"
      - "ira_logs:/workspace/logs"
    command: [ "-config.file=/etc/promtail/promtail.yml", "-config.expand-env=true" ]

  rohan:
    image: raketeneinhorn/tracing-demo-rohan:0.0.1-SNAPSHOT
    volumes:
      - "rohan_logs:/workspace/logs"
    environment:
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317/
      TRACING_DEMO_SIDRA: "${TRACING_DEMO_SIDRA}"
      TRACING_DEMO_IRA: "${TRACING_DEMO_IRA}"
      TRACING_DEMO_ROHAN: "${TRACING_DEMO_ROHAN}"

  rohan_promtail:
    depends_on:
      - loki
    image: grafana/promtail:latest
    volumes:
      - "./promtail/config/:/etc/promtail/"
      - "rohan_logs:/workspace/logs"
    command: [ "-config.file=/etc/promtail/promtail.yml", "-config.expand-env=true" ]

volumes:
  prometheus_data:
  loki_data:
  tempo_data:
  grafana_data:
  sidra_logs:
  ira_logs:
  rohan_logs: