server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
    static_configs:
      - targets:
          - localhost
        labels:
          job: ${SPRING_APPLICATION_NAME}
          __path__: /workspace/logs/*.json